resource_registry:
  OS::TripleO::Compute::Net::SoftwareConfig: /home/stack/templates/nic-configs/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/templates/nic-configs/controller.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/ceph-storage.yaml

parameter_defaults:
  DnsServers: ["10.46.0.32","10.46.0.31"]
  InternalApiNetCidr: 192.168.100.0/24
  StorageNetCidr: 192.168.150.0/24
  StorageMgmtNetCidr: 192.168.200.0/24
  TenantNetCidr: 192.168.250.0/24
  ExternalNetCidr: 10.9.92.0/28
  InternalApiAllocationPools: [{'start': '192.168.100.10', 'end': '192.168.100.200'}]
  StorageAllocationPools: [{'start': '192.168.150.10', 'end': '192.168.150.200'}]
  StorageMgmtAllocationPools: [{'start': '192.168.200.10', 'end': '192.168.200.200'}]
  TenantAllocationPools: [{'start': '192.168.250.10', 'end': '192.168.250.200'}]
  # Use an External allocation pool which will leave room for floating IPs
  ExternalAllocationPools: [{'start': '10.9.92.2', 'end': '10.9.92.13'}]
  # Set to the router gateway on the external network
  ExternalInterfaceDefaultRoute: 10.9.92.14
  ControlPlaneSubnetCidr: "24"
  ControlPlaneDefaultRoute: 192.168.24.1
  EC2MetadataIp: 192.168.24.1
  InternalApiNetworkVlanID: 1101
  StorageNetworkVlanID: 1102
  StorageMgmtNetworkVlanID: 1103
  TenantNetworkVlanID: 1104
  NeutronExternalNetworkBridge: 'br-ex'
  NeutronNetworkType: geneve
  NeutronNetworkVLANRanges: baremetal:1200:1209
  NeutronFlatNetworks: datacentre,baremetal # baremetal needs to be a flat network
  NeutronBridgeMappings: datacentre:br-ex,baremetal:br-baremetal # New 
  NeutronTunnelTypes: geneve
